export * from "@/pages/main/main-page"
export * from "@/pages/main/dashboard/dashboard-page"
export * from "@/pages/main/registros/registros"
export * from "@/pages/main/reportes/reportes"
export * from "@/pages/login/login"
